vercel/hyper-site

- components/Layout.js
onRouteChangeComplete was overwritten twice, breaking the emitter.
> Use RouterEvents

- package.json
- server.js
- yarn.lock
> Use micro instead of express

- components/Layout.js
- components/PluginsList.js
This makes sure Next's Router is used instead of manipulating the history directly.
> Use shallow routing

- plugins.json
Add the `json` object for Shades-of-Purple theme 💜
I was [asked on Twitter](https://twitter.com/markdrew53/status/986101034031419392) to add the theme here. So, fingers crossed. 🤞
---
Name: `shades-of-purple-hyper`
Description: `Professional Hyper™ Terminal theme with hand-picked & bold shades of purple 💜 to go along with your command line usage. Love purple, coz. purple can be genius.`
COLOR | HEX | 
--- | --- | 
Background | #2D2B55 | 
Lite Purple | #6943FF | 
Contrast Yello | #FAD000 | 
Contrast Pink | #FF2C70 | 
Shade of Purple | #B362FF | 
Peace! ✌️
> 🦄NEW: Add Shades-of-Purple theme

- plugins.json
This adds a few of the themes I've written. Let me know if there's anything I need to adjust here! Thanks 😄
> Add new themes

- plugins.json
> Add hyper-opacity plugin

- plugins.json
Feel free to suggest any changes : )
> Add hyper-pokemon theme

- pages/index.js
This pull request updates the API description for the 'notify' helper function. 
The corresponding PR in the hyper branch is: https://github.com/zeit/hyper/pull/2955
> updating the notify API description

- plugins.json
Added the `hyperocean` theme by @klauscfhq! Also this pull request fixes #60 😄
> Added `hyperocean` theme

- components/Footer.js
- components/Header.js
- components/Logo.js
- components/Plugin.js
- components/PluginInfo.js
- package.json
- yarn.lock
Implicit react imports lead to an issue with babel-plugin-inline-react-svg
See https://github.com/airbnb/babel-plugin-inline-react-svg/issues/50
> Update NextJS to v7

- components/PluginInfo.js
- pages/source.js
This PR fix the following issues
<strong>Cannot find //* in *' from unpkg requests<strong>
**The capture of the incorrect plugin data shown on the source page**
> Fix source page issues

- pages/index.js
Docs for https://github.com/zeit/hyper/pull/3193.
> Conventional paths docs

- plugins.json
[hyper-relaxed](https://www.npmjs.com/package/hyper-relaxed)
> Add hyper-relaxed theme

- plugins.json
https://github.com/albertjan/hyper-yes and https://www.npmjs.com/package/hyper-yes
A plugin that takes care of answering 'Terminate batch job (y/n)'.
> Add the hyper-yes plugin.

- plugins.json
Added the xi-hyper theme to the `plugins.json` file.
Let me know if there need to be any changes :)
> Add `xi-hyper` theme

- plugins.json
> Add hyper-launch-menu plugin

- plugins.json
[hyper-afterglow - npm](https://www.npmjs.com/package/hyper-afterglow)
> Add hyper-afterglow theme

- plugins.json
A smart theme inspired by npm
https://www.npmjs.com/package/hyper-npm-theme
> Add hyper-npm-theme

- plugins.json
Adds the [hyper-fading-scrollbar](https://www.npmjs.com/package/hyper-fading-scrollbar) plugin.
> Add hyper-fading-scrollbar plugin

- plugins.json
Adds the [hyper-named-css-colors](https://www.npmjs.com/package/hyper-named-css-colors) theme.
> Add hyper-named-css-colors theme

- plugins.json
https://www.npmjs.com/package/hyper-final-say
> Add plugin `hyper-final-say`

- plugins.json
add details for hyper-shellect, a shell selection menu plugin
> add shellect to plugins.json

- plugins.json
update the preview for hyper-shellect to a nice lil gif instead of a boring static png
> update shellect preview

- pages/index.js
> (#64) display version number on website

- lib/cached-json-fetch.js
Changed the blog location on scale.ai as they don't have a redirect in place.
> Changed the blog location on scale.ai

- now.json
- pages/index.js
This pull request removes the usage of secrets and should remove the requirement of authorization for deployment on subsequent pull requests.
> Remove usage of secrets

- lib/constants.js
Serve the images directly from GitHub instead of going through Cloudinary
> Optimize images

- pages/index.js
With this change, we're making it possible to download Hyper for Apple Chips.
> Provide download link for Apple Silicon

- README.md
- components/download-button/download-button.module.css
- components/download-button/index.js
- package-lock.json
- pages/index.js
- styles/pages/home/installation.module.css
Follow-up to https://github.com/vercel/hyper-site/pull/253.
Inspired by Google Chrome:
> Add dedicated download button for Apple Silicon
